name: Build bertrand-bougon.fr

on:
  push:
    branches:
      - gh-pages

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v2

      - name: 💎 Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: 🔨 Install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true